---
- name: Install and Configure OpenJDK
  hosts: centos
  become: yes

  tasks:
    - name: Enable EPEL repository
      yum:
        name: epel-release
        state: present
        update_cache: yes

    - name: Uninstall OpenJDK
      yum:
        name: java-1.7.0-openjdk
        state: absent

    - name: Install OpenJDK8
      yum:
        name: java-1.8.0-openjdk
        state: present

