---
- name: Install Tomcat
  yum:
    name: tomcat
    state: latest

- name: Install admin packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps

- name: Start Tomcat
  service:
    name: tomcat
    state: started
    enabled: yes

- name: Update Tomcat configurations
  copy:
    src: files/tomcat-users.xml
    dest: /etc/tomcat/tomcat-users.xml
  notify: restart tomcat
